apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api
  namespace: books-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-api
  template:
    metadata:
      labels:
        app: books-api
    spec:
      containers:
      - name: books-api
        image: ghcr.io/OWNER/books-api:latest
        ports:
        - containerPort: 8080
